frame_height: 480
frame_width: 853
height_meters: 15.0
pixels_per_meter: 100
points:
- - 308.5
  - 233
- - 521.5
  - 223
- - 777.5
  - 436
- - 71.5
  - 425
transform_matrix:
- - -2.080754612243064
  - -2.568431474487532
  - 1240.3573314325802
- - -0.5857357376782456
  - -12.47617121254662
  - 3087.6473675971006
- - -0.000429395160622086
  - -0.0058204750933372375
  - 1.0
width_meters: 8.0
